imagemagick:
  enabled: false

exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
  - assets/jupyter/

jekyll-minifier:
  compress_javascript: false
  exclude: ["robots.txt", "assets/js/search/*.js", "**/*"]
